package Interfaz;

import Clases.Empleado;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Ingresar extends javax.swing.JFrame {

    ArrayList<Empleado> lista = new ArrayList<Empleado>();
    Empleado empleado;
    String nombres, apellidos, cedula, direccion, email, genero, departamento;
    int celular, telefono_fijo, salario_base, valorH, valorHED, valorHEN, HED, HEN, TotalApo, fila;

    public Ingresar() {
        initComponents();
        VerRegistro();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        InCedula = new javax.swing.JTextField();
        InNombres = new javax.swing.JTextField();
        InApellidos = new javax.swing.JTextField();
        InCelular = new javax.swing.JTextField();
        InGenero = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        InDepto = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        InDireccion = new javax.swing.JTextField();
        InTelFijo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        InEmail = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        InValorH = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        InHED = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        InHEN = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        InValorHED = new javax.swing.JTextField();
        InValorHEN = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        InSubTras = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        InSalFinal = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        InPension = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        InSalud = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        InTotalApo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePersonas = new javax.swing.JTable();
        InLimpiar = new javax.swing.JButton();
        InGuardar = new javax.swing.JButton();
        InCalcular = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        InSalBase = new javax.swing.JTextField();
        InModificar = new javax.swing.JButton();
        InEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(1034, 577));
        jPanel1.setPreferredSize(new java.awt.Dimension(1034, 577));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Palatino Linotype", 2, 36)); // NOI18N
        jLabel1.setText("Empleado");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 50, 280, 60));

        jLabel2.setFont(new java.awt.Font("Segoe UI Symbol", 2, 14)); // NOI18N
        jLabel2.setText("Cedula:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, 60, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Symbol", 2, 14)); // NOI18N
        jLabel3.setText("Nombres:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, 70, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Symbol", 2, 14)); // NOI18N
        jLabel4.setText("Apellidos:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, 70, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI Symbol", 2, 14)); // NOI18N
        jLabel5.setText("Celular:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, 50, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI Symbol", 2, 14)); // NOI18N
        jLabel6.setText("Genero:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, 60, -1));

        InCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InCedulaActionPerformed(evt);
            }
        });
        jPanel1.add(InCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, 100, 20));

        InNombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InNombresActionPerformed(evt);
            }
        });
        jPanel1.add(InNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, 100, -1));
        jPanel1.add(InApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 170, 100, -1));
        jPanel1.add(InCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 200, 100, -1));

        InGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Hombre", "Mujer" }));
        InGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InGeneroActionPerformed(evt);
            }
        });
        jPanel1.add(InGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 230, 100, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI Symbol", 2, 14)); // NOI18N
        jLabel7.setText("Departamento:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 110, 100, -1));

        InDepto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Gerencia", "Administración", "Planta" }));
        InDepto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InDeptoActionPerformed(evt);
            }
        });
        jPanel1.add(InDepto, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 110, 100, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI Symbol", 2, 14)); // NOI18N
        jLabel8.setText("Dirección:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 190, 80, -1));
        jPanel1.add(InDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 190, 110, -1));
        jPanel1.add(InTelFijo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 220, 110, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI Symbol", 2, 14)); // NOI18N
        jLabel9.setText("Teléfono Fijo:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 220, 80, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI Symbol", 2, 14)); // NOI18N
        jLabel10.setText("E-mail:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 250, 80, -1));
        jPanel1.add(InEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 250, 110, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI Symbol", 2, 14)); // NOI18N
        jLabel11.setText("Valor Hora");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 320, 80, -1));

        InValorH.setEditable(false);
        InValorH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InValorHActionPerformed(evt);
            }
        });
        jPanel1.add(InValorH, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 320, 110, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI Symbol", 2, 14)); // NOI18N
        jLabel12.setText("Horas extras D:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 310, 100, -1));
        jPanel1.add(InHED, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 310, 110, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI Symbol", 2, 14)); // NOI18N
        jLabel13.setText("Horas extras N:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 340, 100, -1));
        jPanel1.add(InHEN, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 340, 110, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI Symbol", 2, 14)); // NOI18N
        jLabel14.setText("Valor H.E.D:");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 320, 100, -1));

        InValorHED.setEditable(false);
        jPanel1.add(InValorHED, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 320, 110, -1));

        InValorHEN.setEditable(false);
        jPanel1.add(InValorHEN, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 350, 110, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI Symbol", 3, 14)); // NOI18N
        jLabel15.setText("Aportes");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 390, 100, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI Symbol", 2, 14)); // NOI18N
        jLabel16.setText(" Subsidio de trasnporte:");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 370, 160, -1));

        InSubTras.setEditable(false);
        jPanel1.add(InSubTras, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 370, 110, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI Symbol", 2, 14)); // NOI18N
        jLabel17.setText("Saliro Final:");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 450, 80, -1));

        InSalFinal.setEditable(false);
        jPanel1.add(InSalFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 450, 110, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI Symbol", 2, 14)); // NOI18N
        jLabel18.setText("Valor H.E.N:");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 350, 100, -1));

        InPension.setEditable(false);
        jPanel1.add(InPension, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 420, 110, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI Symbol", 2, 14)); // NOI18N
        jLabel19.setText("Pensión:");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 420, 100, -1));

        jLabel20.setFont(new java.awt.Font("Segoe UI Symbol", 2, 14)); // NOI18N
        jLabel20.setText("Salud:");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 450, 100, -1));

        InSalud.setEditable(false);
        jPanel1.add(InSalud, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 450, 110, -1));

        jLabel21.setFont(new java.awt.Font("Segoe UI Symbol", 2, 14)); // NOI18N
        jLabel21.setText("Total Aportes:");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 480, 100, -1));

        InTotalApo.setEditable(false);
        jPanel1.add(InTotalApo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 480, 110, -1));

        jTablePersonas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Cedula", "Nombre", "Apellido", "Genero", "Celular", "Direccion", "Telefono Fijo", "E-mail", "Salario Base", "Aportes", "Departamento", "HED", "HEN", "Salario FInal"
            }
        ));
        jTablePersonas.setShowGrid(true);
        jTablePersonas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablePersonasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTablePersonas);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 550, 1120, 120));

        InLimpiar.setFont(new java.awt.Font("Segoe UI Symbol", 2, 18)); // NOI18N
        InLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/limpiar.png"))); // NOI18N
        InLimpiar.setText("Limpiar");
        InLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InLimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(InLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 680, 141, -1));

        InGuardar.setFont(new java.awt.Font("Segoe UI Symbol", 2, 18)); // NOI18N
        InGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/disquete.png"))); // NOI18N
        InGuardar.setText("Ingresar");
        InGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(InGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 141, -1));

        InCalcular.setFont(new java.awt.Font("Segoe UI Symbol", 2, 18)); // NOI18N
        InCalcular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/presupuesto.png"))); // NOI18N
        InCalcular.setLabel("Calcular");
        InCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InCalcularActionPerformed(evt);
            }
        });
        jPanel1.add(InCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 680, 141, -1));

        jLabel22.setFont(new java.awt.Font("Segoe UI Symbol", 2, 14)); // NOI18N
        jLabel22.setText("Saliro Base:");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 270, 80, -1));

        InSalBase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InSalBaseActionPerformed(evt);
            }
        });
        jPanel1.add(InSalBase, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 270, 110, -1));

        InModificar.setFont(new java.awt.Font("Segoe UI Symbol", 2, 18)); // NOI18N
        InModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/disquete.png"))); // NOI18N
        InModificar.setText("Modificar");
        InModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InModificarActionPerformed(evt);
            }
        });
        jPanel1.add(InModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 141, -1));

        InEliminar.setFont(new java.awt.Font("Segoe UI Symbol", 2, 18)); // NOI18N
        InEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/disquete.png"))); // NOI18N
        InEliminar.setText("Eliminar");
        InEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(InEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 141, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 790));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void InDeptoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InDeptoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InDeptoActionPerformed

    private void InGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InGeneroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InGeneroActionPerformed

    private void InNombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InNombresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InNombresActionPerformed

    private void InLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InLimpiarActionPerformed
        limpiar();
    }//GEN-LAST:event_InLimpiarActionPerformed

    private void InGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InGuardarActionPerformed
        try {
            int estado = 0;
            capturar();
            int res = buscaProductoEnModelo(cedula, (DefaultTableModel) jTablePersonas.getModel());
            if (res == 1) {
                if (Integer.parseInt(cedula) > 0 && celular > 0 && telefono_fijo > 0 && salario_base > 0 && HED > 0 && HEN > 0) {
                    if (HED <= 60 && HEN <= 60) {
                        if ((departamento == "Gerencia" && salario_base > 3000000)
                                || (departamento == "Administración" && (salario_base >= 2000000 && salario_base <= 3000000))
                                || (departamento == "Planta" && (salario_base >= 200000 && salario_base <= 1000000))) {
                            crear();
                        } else {
                            JOptionPane.showMessageDialog(null, "No coincide el salario con el departamento", "ERROR", 0);
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "Las horas extras no pueden ser mayor a 60 horas", "SALIDA", JOptionPane.INFORMATION_MESSAGE);
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "No pueden ser numeros negativos", "SALIDA", JOptionPane.INFORMATION_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Ya existe la cedula", "SALIDA", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "VERIFICAR LOS CAMPOS", "SALIDA", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_InGuardarActionPerformed

    private int buscaProductoEnModelo(String cedula, DefaultTableModel modelo) {
        if (cedula != null && modelo != null) {
            for (int renglon = 0; renglon < modelo.getRowCount(); renglon++) {
                String cedulaEnRenglon = (String) modelo.getValueAt(renglon, 0);
                if (cedula.equals(cedulaEnRenglon)) {
                    return -1;
                }
            }
        }
        return 1;
    }

    private void InCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InCedulaActionPerformed

    private void InCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InCalcularActionPerformed
        calcular();
    }//GEN-LAST:event_InCalcularActionPerformed

    private void InSalBaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InSalBaseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InSalBaseActionPerformed

    private void InValorHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InValorHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InValorHActionPerformed

    private void InModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InModificarActionPerformed
        try {
            if (fila == -1) {
                JOptionPane.showMessageDialog(null, "No se ha seleccionado una fila", "SALIDA", JOptionPane.INFORMATION_MESSAGE);
            } else {
                lista.remove(fila);
                crear();
                fila = -1;
                JOptionPane.showMessageDialog(null, "Empleado modificado correctamente", "SALIDA", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "SELECCIONE UNA FILA", "SALIDA", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_InModificarActionPerformed

    private void InEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InEliminarActionPerformed
        try {
            if (fila == -1) {
                JOptionPane.showMessageDialog(null, "No se ha seleccionado una fila", "SALIDA", JOptionPane.INFORMATION_MESSAGE);
            } else {
                int res = JOptionPane.showConfirmDialog(null, "¿Esta seguro?", "Alerta!", JOptionPane.YES_NO_OPTION);
                if (res != 1) {
                    lista.remove(fila);
                    limpiar();
                    VerRegistro();
                    fila = -1;
                    JOptionPane.showMessageDialog(null, "Empleado eliminado correctamente", "SALIDA", JOptionPane.INFORMATION_MESSAGE);
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "SELECCIONE UNA FILA", "SALIDA", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_InEliminarActionPerformed

    private void jTablePersonasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablePersonasMouseClicked
        fila = jTablePersonas.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(null, "No se ha seleccionado una fila", "SALIDA", JOptionPane.INFORMATION_MESSAGE);
        } else {
            String cedu = (String) jTablePersonas.getValueAt(fila, 0);
            String nom = (String) jTablePersonas.getValueAt(fila, 1);
            String apell = (String) jTablePersonas.getValueAt(fila, 2);
            String cel = (String) jTablePersonas.getValueAt(fila, 3);
            String direcc = (String) jTablePersonas.getValueAt(fila, 4);
            String tel = (String) jTablePersonas.getValueAt(fila, 5);
            String correo = (String) jTablePersonas.getValueAt(fila, 6);
            String sala_bas = (String) jTablePersonas.getValueAt(fila, 7);
            String gen = (String) lista.get(fila).getGenero();
            String depart = (String) lista.get(fila).getDepartamento();
            String hed = Integer.toString(lista.get(fila).getHED());
            String hen = Integer.toString(lista.get(fila).getHEN());

            InCedula.setText(cedu);
            InNombres.setText(nom);
            InApellidos.setText(apell);
            InCelular.setText(cel);
            InDireccion.setText(direcc);
            InTelFijo.setText(tel);
            InEmail.setText(correo);
            InSalBase.setText(sala_bas);
            InGenero.setSelectedItem(gen);
            InDepto.setSelectedItem(depart);
            InHED.setText(hed);
            InHEN.setText(hen);
        }
    }//GEN-LAST:event_jTablePersonasMouseClicked

    private void VerRegistro() {

        String Matriz[][] = new String[lista.size()][10];

        for (int i = 0; i < lista.size(); i++) {

            Matriz[i][0] = lista.get(i).getCedula();
            Matriz[i][1] = lista.get(i).getNombres();
            Matriz[i][2] = lista.get(i).getApellidos();
            Matriz[i][3] = Integer.toString(lista.get(i).getCelular());
            Matriz[i][4] = lista.get(i).getDireccion();
            Matriz[i][5] = Integer.toString(lista.get(i).getTelefono_fijo());
            Matriz[i][6] = lista.get(i).getEmail();
            Matriz[i][7] = Integer.toString(lista.get(i).getSalario_base());
            Matriz[i][8] = Double.toString(lista.get(i).getAportes());
            Matriz[i][9] = Double.toString(lista.get(i).getSalario_final());

        }

        jTablePersonas.setModel(new javax.swing.table.DefaultTableModel(
                Matriz,
                new String[]{
                    "Cedula", "Nombre", "Apellido", "Celular", "Direccion", "Telefono Fijo", "E-mail", "Salario Base", "Aportes", "Salario Final"
                }
        ));
    }

    public void capturar() {
        nombres = InNombres.getText();
        apellidos = InApellidos.getText();
        cedula = InCedula.getText();
        direccion = InDireccion.getText();
        email = InEmail.getText();
        celular = Integer.parseInt(InCelular.getText());
        telefono_fijo = Integer.parseInt(InTelFijo.getText());
        salario_base = Integer.parseInt(InSalBase.getText());
        HED = Integer.parseInt(InHED.getText());
        HEN = Integer.parseInt(InHEN.getText());
        genero = (String) InGenero.getSelectedItem();
        departamento = (String) InDepto.getSelectedItem();
    }

    public void calcular() {
        capturar();
        empleado = new Empleado(nombres, apellidos, cedula, direccion, email, celular, telefono_fijo, salario_base, HED, HEN, genero, departamento);
        empleado.setSalario_base(salario_base);
        InSubTras.setText(Double.toString(empleado.getSubTras()));
        InValorH.setText(Double.toString(empleado.getvalorH()));
        InValorHED.setText(Double.toString(empleado.getValorHED()));
        InValorHEN.setText(Double.toString(empleado.getValorHEN()));
        InPension.setText(Double.toString(empleado.getPension()));
        InSalud.setText(Double.toString(empleado.getSalud()));
        InTotalApo.setText(Double.toString(empleado.getAportes()));
        InSalFinal.setText(Double.toString(empleado.getSalario_final()));
    }

    public void limpiar() {
        InCedula.setText("");
        InNombres.setText("");
        InApellidos.setText("");
        InCelular.setText("");
        InGenero.setSelectedIndex(0);
        InValorH.setText("");
        InSalFinal.setText("");
        InSalBase.setText("");
        InDepto.setSelectedIndex(0);
        InDireccion.setText("");
        InTelFijo.setText("");
        InEmail.setText("");
        InValorHED.setText("");
        InValorHEN.setText("");
        InPension.setText("");
        InSalud.setText("");
        InTotalApo.setText("");
        InHED.setText("");
        InHEN.setText("");
        InSubTras.setText("");
    }

    public void crear() {
        capturar();
        empleado = new Empleado(nombres, apellidos, cedula, direccion, email, celular, telefono_fijo, salario_base, HED, HEN, genero, departamento);
        calcular();
        lista.add(empleado);
        limpiar();
        VerRegistro();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField InApellidos;
    private javax.swing.JButton InCalcular;
    private javax.swing.JTextField InCedula;
    private javax.swing.JTextField InCelular;
    private javax.swing.JComboBox<String> InDepto;
    private javax.swing.JTextField InDireccion;
    private javax.swing.JButton InEliminar;
    private javax.swing.JTextField InEmail;
    private javax.swing.JComboBox<String> InGenero;
    private javax.swing.JButton InGuardar;
    private javax.swing.JTextField InHED;
    private javax.swing.JTextField InHEN;
    private javax.swing.JButton InLimpiar;
    private javax.swing.JButton InModificar;
    private javax.swing.JTextField InNombres;
    private javax.swing.JTextField InPension;
    private javax.swing.JTextField InSalBase;
    private javax.swing.JTextField InSalFinal;
    private javax.swing.JTextField InSalud;
    private javax.swing.JTextField InSubTras;
    private javax.swing.JTextField InTelFijo;
    private javax.swing.JTextField InTotalApo;
    private javax.swing.JTextField InValorH;
    private javax.swing.JTextField InValorHED;
    private javax.swing.JTextField InValorHEN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePersonas;
    // End of variables declaration//GEN-END:variables
}
