/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import Clases.Empleado;

/**
 *
 * @author Nicolle
 */
public class Modificar extends javax.swing.JFrame {

    /**
     * Creates new form Modificar
     */
    public Modificar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ModCedula = new javax.swing.JTextField();
        ModNombres = new javax.swing.JTextField();
        ModApellidos = new javax.swing.JTextField();
        ModCelular = new javax.swing.JTextField();
        ModGenero = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        ModDepto = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        ModDireccion = new javax.swing.JTextField();
        ModTelFijo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        ModEmail = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        ModSalBase = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        ModHED = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        ModHEN = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        ModValorHED = new javax.swing.JTextField();
        ModValorHEN = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        ModSubTras = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        ModSalFinal = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        ModPension = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        ModSalud = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        ModTotalApo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        ModLimpiar = new javax.swing.JButton();
        ModMenú = new javax.swing.JButton();
        ModGuardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1033, 577));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(1034, 577));
        jPanel1.setPreferredSize(new java.awt.Dimension(1034, 577));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Palatino Linotype", 2, 36)); // NOI18N
        jLabel1.setText("Modificar Empleado");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 310, 60));

        jLabel2.setFont(new java.awt.Font("Segoe UI Symbol", 2, 14)); // NOI18N
        jLabel2.setText("Cedula:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 60, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Symbol", 2, 14)); // NOI18N
        jLabel3.setText("Nombres:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 70, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Symbol", 2, 14)); // NOI18N
        jLabel4.setText("Apellidos:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 70, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI Symbol", 2, 14)); // NOI18N
        jLabel5.setText("Celular:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 50, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI Symbol", 2, 14)); // NOI18N
        jLabel6.setText("Genero:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 60, -1));
        jPanel1.add(ModCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 100, -1));

        ModNombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModNombresActionPerformed(evt);
            }
        });
        jPanel1.add(ModNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 100, -1));
        jPanel1.add(ModApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 100, -1));
        jPanel1.add(ModCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 100, -1));

        ModGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ModGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModGeneroActionPerformed(evt);
            }
        });
        jPanel1.add(ModGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 100, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI Symbol", 2, 14)); // NOI18N
        jLabel7.setText("Departamento:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 80, 100, -1));

        ModDepto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ModDepto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModDeptoActionPerformed(evt);
            }
        });
        jPanel1.add(ModDepto, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 80, 100, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI Symbol", 2, 14)); // NOI18N
        jLabel8.setText("Dirección:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 160, 80, -1));
        jPanel1.add(ModDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 160, 110, -1));
        jPanel1.add(ModTelFijo, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 190, 110, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI Symbol", 2, 14)); // NOI18N
        jLabel9.setText("Teléfono Fijo:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 190, 80, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI Symbol", 2, 14)); // NOI18N
        jLabel10.setText("E-mail:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 220, 80, -1));
        jPanel1.add(ModEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 220, 110, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI Symbol", 2, 14)); // NOI18N
        jLabel11.setText("Saliro Base:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 240, 80, -1));
        jPanel1.add(ModSalBase, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 240, 110, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI Symbol", 2, 14)); // NOI18N
        jLabel12.setText("Horas extras D:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 100, -1));
        jPanel1.add(ModHED, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 110, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI Symbol", 2, 14)); // NOI18N
        jLabel13.setText("Horas extras N:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, 100, -1));
        jPanel1.add(ModHEN, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, 110, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI Symbol", 2, 14)); // NOI18N
        jLabel14.setText("Valor H.E.D:");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 290, 100, -1));
        jPanel1.add(ModValorHED, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 290, 110, -1));
        jPanel1.add(ModValorHEN, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 320, 110, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI Symbol", 3, 14)); // NOI18N
        jLabel15.setText("Aportes");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 360, 100, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI Symbol", 2, 14)); // NOI18N
        jLabel16.setText(" Subsidio de trasnporte:");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 160, -1));
        jPanel1.add(ModSubTras, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, 110, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI Symbol", 2, 14)); // NOI18N
        jLabel17.setText("Saliro Final:");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 360, 80, -1));
        jPanel1.add(ModSalFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 360, 110, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI Symbol", 2, 14)); // NOI18N
        jLabel18.setText("Valor H.E.N:");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 320, 100, -1));
        jPanel1.add(ModPension, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 390, 110, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI Symbol", 2, 14)); // NOI18N
        jLabel19.setText("Pensión:");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 390, 100, -1));

        jLabel20.setFont(new java.awt.Font("Segoe UI Symbol", 2, 14)); // NOI18N
        jLabel20.setText("Salud:");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 420, 100, -1));
        jPanel1.add(ModSalud, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 420, 110, -1));

        jLabel21.setFont(new java.awt.Font("Segoe UI Symbol", 2, 14)); // NOI18N
        jLabel21.setText("Total Aportes:");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 450, 100, -1));
        jPanel1.add(ModTotalApo, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 450, 110, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Cedula", "Nombre", "Apellido", "Celular", "Genero", "Dep/to", "Direccion", "Telefono Fijo", "E-mail", "Salario Base", "Aportes", "Salario Final"
            }
        ));
        jTable1.setShowGrid(true);
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, 960, 120));

        ModLimpiar.setFont(new java.awt.Font("Segoe UI Symbol", 2, 18)); // NOI18N
        ModLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/limpiar.png"))); // NOI18N
        ModLimpiar.setText("Limpiar");
        ModLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModLimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(ModLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 650, 141, -1));

        ModMenú.setFont(new java.awt.Font("Segoe UI Symbol", 2, 18)); // NOI18N
        ModMenú.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/casa.png"))); // NOI18N
        ModMenú.setText("Menú principal");
        ModMenú.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModMenúActionPerformed(evt);
            }
        });
        jPanel1.add(ModMenú, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 650, 190, -1));

        ModGuardar.setFont(new java.awt.Font("Segoe UI Symbol", 2, 18)); // NOI18N
        ModGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/disquete.png"))); // NOI18N
        ModGuardar.setText("Guardar");
        ModGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(ModGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 650, 141, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 709));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ModGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModGuardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ModGuardarActionPerformed

    private void ModMenúActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModMenúActionPerformed
        Diseño ver = new Diseño();
        ver.setVisible(true);
        this.setVisible(false);
        this.setLocationRelativeTo(null);
    }//GEN-LAST:event_ModMenúActionPerformed

    private void ModLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModLimpiarActionPerformed
        Diseño ver = new Diseño();
        ver.setVisible(true);
        this.setVisible(false);
        this.setLocationRelativeTo(null);
    }//GEN-LAST:event_ModLimpiarActionPerformed

    private void ModDeptoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModDeptoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ModDeptoActionPerformed

    private void ModGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModGeneroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ModGeneroActionPerformed

    private void ModNombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModNombresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ModNombresActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ModApellidos;
    private javax.swing.JTextField ModCedula;
    private javax.swing.JTextField ModCelular;
    private javax.swing.JComboBox<String> ModDepto;
    private javax.swing.JTextField ModDireccion;
    private javax.swing.JTextField ModEmail;
    private javax.swing.JComboBox<String> ModGenero;
    private javax.swing.JButton ModGuardar;
    private javax.swing.JTextField ModHED;
    private javax.swing.JTextField ModHEN;
    private javax.swing.JButton ModLimpiar;
    private javax.swing.JButton ModMenú;
    private javax.swing.JTextField ModNombres;
    private javax.swing.JTextField ModPension;
    private javax.swing.JTextField ModSalBase;
    private javax.swing.JTextField ModSalFinal;
    private javax.swing.JTextField ModSalud;
    private javax.swing.JTextField ModSubTras;
    private javax.swing.JTextField ModTelFijo;
    private javax.swing.JTextField ModTotalApo;
    private javax.swing.JTextField ModValorHED;
    private javax.swing.JTextField ModValorHEN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
