/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

/**
 *
 * @author Nicolle
 */
public class Reportes extends javax.swing.JFrame {

    /**
     * Creates new form Reportes
     */
    public Reportes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Listado1 = new javax.swing.JButton();
        Listados2 = new javax.swing.JButton();
        Listado3 = new javax.swing.JButton();
        SubsidioR = new javax.swing.JButton();
        AportesR = new javax.swing.JButton();
        DireEmailR = new javax.swing.JButton();
        ModMenú1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(1033, 577));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Palatino Linotype", 3, 36)); // NOI18N
        jLabel1.setText("Reportes");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, 150, 60));

        Listado1.setFont(new java.awt.Font("Segoe UI Symbol", 2, 18)); // NOI18N
        Listado1.setText("Listado de área de gerencia");
        Listado1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Listado1ActionPerformed(evt);
            }
        });
        jPanel1.add(Listado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, 310, -1));

        Listados2.setFont(new java.awt.Font("Segoe UI Symbol", 2, 18)); // NOI18N
        Listados2.setText("Listado de área de administrativo");
        Listados2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Listados2ActionPerformed(evt);
            }
        });
        jPanel1.add(Listados2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, 310, -1));

        Listado3.setFont(new java.awt.Font("Segoe UI Symbol", 2, 18)); // NOI18N
        Listado3.setText("Listado de área de planta");
        Listado3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Listado3ActionPerformed(evt);
            }
        });
        jPanel1.add(Listado3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 250, 310, -1));

        SubsidioR.setFont(new java.awt.Font("Segoe UI Symbol", 2, 18)); // NOI18N
        SubsidioR.setText("Subsidio de trasnporte");
        SubsidioR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubsidioRActionPerformed(evt);
            }
        });
        jPanel1.add(SubsidioR, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 300, 310, -1));

        AportesR.setFont(new java.awt.Font("Segoe UI Symbol", 2, 18)); // NOI18N
        AportesR.setText("Aportes a pensión y salud");
        AportesR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AportesRActionPerformed(evt);
            }
        });
        jPanel1.add(AportesR, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 360, 310, -1));

        DireEmailR.setFont(new java.awt.Font("Segoe UI Symbol", 2, 18)); // NOI18N
        DireEmailR.setText("Dirección - Email - Celular");
        DireEmailR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DireEmailRActionPerformed(evt);
            }
        });
        jPanel1.add(DireEmailR, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 410, 310, -1));

        ModMenú1.setFont(new java.awt.Font("Segoe UI Symbol", 2, 18)); // NOI18N
        ModMenú1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/casa.png"))); // NOI18N
        ModMenú1.setText("Menú principal");
        ModMenú1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModMenú1ActionPerformed(evt);
            }
        });
        jPanel1.add(ModMenú1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 520, 190, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Listado1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Listado1ActionPerformed
        
    }//GEN-LAST:event_Listado1ActionPerformed

    private void Listados2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Listados2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Listados2ActionPerformed

    private void Listado3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Listado3ActionPerformed
        
    }//GEN-LAST:event_Listado3ActionPerformed

    private void SubsidioRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubsidioRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SubsidioRActionPerformed

    private void AportesRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AportesRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AportesRActionPerformed

    private void DireEmailRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DireEmailRActionPerformed
       
    }//GEN-LAST:event_DireEmailRActionPerformed

    private void ModMenú1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModMenú1ActionPerformed
        Diseño ver = new Diseño();
        ver.setVisible(true);
        this.setVisible(false);
        this.setLocationRelativeTo(null);
    }//GEN-LAST:event_ModMenú1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reportes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AportesR;
    private javax.swing.JButton DireEmailR;
    private javax.swing.JButton Listado1;
    private javax.swing.JButton Listado3;
    private javax.swing.JButton Listados2;
    private javax.swing.JButton ModMenú1;
    private javax.swing.JButton SubsidioR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
